services:

  products_service:
    container_name: inventory-service
    build:
      context: ./inventory-service
    depends_on:
      - db
    env_file:
      - ./inventory-service/.env.prod

    
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27027:27017"
    env_file:
      - ./inventory-service/.env
    volumes:
      - mongo_data:/data/db
