version: '3.8'

services:
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8003:8003"
    environment:
      - HTTP_PORT=8003
      - INVENTORY_SERVICE=inventory-service:8001
      - ORDER_SERVICE=order-service:8002
      - INVENTORY_SERVICE_GRPC=inventory-service:8001
      - ORDER_SERVICE_GRPC=order-service:8002
    depends_on:
      - inventory-service
      - order-service
      - statistics-service

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8001:8001"
    environment:
      - HTTP_PORT=8001
      - GIN_MODE=release
      - MONGO_DB=assignment
      - MONGO_DB_URI=mongodb://mongo:27017
      - NATS_URL=nats://nats:4222
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
    depends_on:
      - mongo

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8002:8002"
    environment:
      - HTTP_PORT=8002
      - GIN_MODE=release
      - MONGO_DB=assignment
      - MONGO_DB_URI=mongodb://mongo:27017
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db

  statistics-service:
    build:
      context: ./statistics-service
    container_name: statistics-service
    ports:
      - "8004:8004"
    environment:
      - HTTP_PORT=8004
      - GIN_MODE=release
      - MONGO_DB=assignment
      - MONGO_DB_URI=mongodb://mongo:27017
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongo
      - nats

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    environment:
      - NATS_SERVER=1

volumes:
  mongo-data:
