// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrderStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderStatisticsRequest) Reset() {
	*x = UserOrderStatisticsRequest{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsRequest) ProtoMessage() {}

func (x *UserOrderStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UserOrderStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserOrderStatisticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders        int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	HourlyDistribution map[string]int32       `protobuf:"bytes,2,rep,name=hourly_distribution,json=hourlyDistribution,proto3" json:"hourly_distribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserOrderStatisticsResponse) Reset() {
	*x = UserOrderStatisticsResponse{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsResponse) ProtoMessage() {}

func (x *UserOrderStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *UserOrderStatisticsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserOrderStatisticsResponse) GetHourlyDistribution() map[string]int32 {
	if x != nil {
		return x.HourlyDistribution
	}
	return nil
}

type UserStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsRequest) Reset() {
	*x = UserStatisticsRequest{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsRequest) ProtoMessage() {}

func (x *UserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *UserStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatisticsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalItemsPurchased  int32                  `protobuf:"varint,1,opt,name=total_items_purchased,json=totalItemsPurchased,proto3" json:"total_items_purchased,omitempty"`
	AverageOrderValue    float64                `protobuf:"fixed64,2,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	MostPurchasedItem    string                 `protobuf:"bytes,3,opt,name=most_purchased_item,json=mostPurchasedItem,proto3" json:"most_purchased_item,omitempty"`
	TotalCompletedOrders int32                  `protobuf:"varint,4,opt,name=total_completed_orders,json=totalCompletedOrders,proto3" json:"total_completed_orders,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserStatisticsResponse) Reset() {
	*x = UserStatisticsResponse{}
	mi := &file_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsResponse) ProtoMessage() {}

func (x *UserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *UserStatisticsResponse) GetTotalItemsPurchased() int32 {
	if x != nil {
		return x.TotalItemsPurchased
	}
	return 0
}

func (x *UserStatisticsResponse) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *UserStatisticsResponse) GetMostPurchasedItem() string {
	if x != nil {
		return x.MostPurchasedItem
	}
	return ""
}

func (x *UserStatisticsResponse) GetTotalCompletedOrders() int32 {
	if x != nil {
		return x.TotalCompletedOrders
	}
	return 0
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *OrderEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *OrderEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderEvent) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{5}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type InventoryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryEvent) Reset() {
	*x = InventoryEvent{}
	mi := &file_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryEvent) ProtoMessage() {}

func (x *InventoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryEvent.ProtoReflect.Descriptor instead.
func (*InventoryEvent) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *InventoryEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *InventoryEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InventoryEvent) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *InventoryEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InventoryEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\n" +
	"statistics\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x1aUserOrderStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf9\x01\n" +
	"\x1bUserOrderStatisticsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12p\n" +
	"\x13hourly_distribution\x18\x02 \x03(\v2?.statistics.UserOrderStatisticsResponse.HourlyDistributionEntryR\x12hourlyDistribution\x1aE\n" +
	"\x17HourlyDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"0\n" +
	"\x15UserStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe2\x01\n" +
	"\x16UserStatisticsResponse\x122\n" +
	"\x15total_items_purchased\x18\x01 \x01(\x05R\x13totalItemsPurchased\x12.\n" +
	"\x13average_order_value\x18\x02 \x01(\x01R\x11averageOrderValue\x12.\n" +
	"\x13most_purchased_item\x18\x03 \x01(\tR\x11mostPurchasedItem\x124\n" +
	"\x16total_completed_orders\x18\x04 \x01(\x05R\x14totalCompletedOrders\"\xca\x02\n" +
	"\n" +
	"OrderEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12+\n" +
	"\x05items\x18\x05 \x03(\v2\x15.statistics.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\xcf\x01\n" +
	"\x0eInventoryEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xdb\x01\n" +
	"\x11StatisticsService\x12j\n" +
	"\x17GetUserOrdersStatistics\x12&.statistics.UserOrderStatisticsRequest\x1a'.statistics.UserOrderStatisticsResponse\x12Z\n" +
	"\x11GetUserStatistics\x12!.statistics.UserStatisticsRequest\x1a\".statistics.UserStatisticsResponseBMZKgithub.com/mephirious/advanced-programming-2/statistics-service/proto;protob\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stats_proto_goTypes = []any{
	(*UserOrderStatisticsRequest)(nil),  // 0: statistics.UserOrderStatisticsRequest
	(*UserOrderStatisticsResponse)(nil), // 1: statistics.UserOrderStatisticsResponse
	(*UserStatisticsRequest)(nil),       // 2: statistics.UserStatisticsRequest
	(*UserStatisticsResponse)(nil),      // 3: statistics.UserStatisticsResponse
	(*OrderEvent)(nil),                  // 4: statistics.OrderEvent
	(*OrderItem)(nil),                   // 5: statistics.OrderItem
	(*InventoryEvent)(nil),              // 6: statistics.InventoryEvent
	nil,                                 // 7: statistics.UserOrderStatisticsResponse.HourlyDistributionEntry
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_stats_proto_depIdxs = []int32{
	7, // 0: statistics.UserOrderStatisticsResponse.hourly_distribution:type_name -> statistics.UserOrderStatisticsResponse.HourlyDistributionEntry
	5, // 1: statistics.OrderEvent.items:type_name -> statistics.OrderItem
	8, // 2: statistics.OrderEvent.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: statistics.OrderEvent.updated_at:type_name -> google.protobuf.Timestamp
	8, // 4: statistics.InventoryEvent.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: statistics.StatisticsService.GetUserOrdersStatistics:input_type -> statistics.UserOrderStatisticsRequest
	2, // 6: statistics.StatisticsService.GetUserStatistics:input_type -> statistics.UserStatisticsRequest
	1, // 7: statistics.StatisticsService.GetUserOrdersStatistics:output_type -> statistics.UserOrderStatisticsResponse
	3, // 8: statistics.StatisticsService.GetUserStatistics:output_type -> statistics.UserStatisticsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
